services:
  - type: web
    name: gorsel-uygulama
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_app:app"
    envVars:
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/outputs
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
