services:
  - type: web
    name: gorsel-uygulama
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install Flask==2.3.3 gunicorn==21.2.0 requests==2.31.0 Werkzeug==2.3.7 uuid==1.30 python-dotenv==1.0.0
      pip install --upgrade --force-reinstall pillow-simd || pip install --upgrade Pillow
      mkdir -p /tmp/uploads /tmp/outputs
      cp *.ttf *.png /tmp/
    startCommand: "gunicorn web_app:app --workers 2 --threads 4 --timeout 300 --max-requests 100"
    envVars:
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/outputs
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
    disk:
      name: data
      mountPath: /tmp
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: false
