services:
  - type: web
    name: gorsel-uygulama
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/uploads /tmp/outputs
    startCommand: "gunicorn web_app:app --timeout 120"
    envVars:
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: OUTPUT_FOLDER
        value: /tmp/outputs
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "true"
    disk:
      name: data
      mountPath: /tmp
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: false
